# A YAML file is essentially a sequence of documents separated by --- lines.
# Each document is parsed separately to a flattened map.

# The first section contains application wide settings applied regardless of a profile

# JMX
spring:
  jmx:
    enabled: true
  cloud:
    config:
      # System properties should take preference
      overrideSystemProperties: false
  
  # Datasource configuration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1:11000/mem:test
  
  # Jackson Configuration
  jackson:
    serialization:
      # Output dates in the ISO format rather than millis since the epoch
      WRITE_DATES_AS_TIMESTAMPS: false
  
  # Java Persistence API configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
# Logging configuration
logging:
  level:
    root: INFO

# Tomcat Server settings
server:
  address: 0.0.0.0
  port: 0
  servletPath: /
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %t \"%r\" %s %b"
    basedir: /var/log

# Kafka Server settings
kafka:
  broker:
    list: localhost:9092

# Zookeeper settings
zookeeper:
   connect: localhost:2181

# Management endpoints
management:
  context-path: /manage

endpoints:
  health:
    sensitive: false
  info:
    sensitive: false
  shutdown:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:PID-${PID}
    statusPageUrlPath: /manage/info/
    healthCheckUrlPath: /manage/health/

discovery:
  authentication:
    jwtSigningKey: theSecretKey
    loginServerEnabled: false
    defaultPolicy: OPEN
