# A YAML file is essentially a sequence of documents separated by --- lines.
# Each document is parsed separately to a flattened map.

# The first section contains application wide settings applied regardless of a profile

# JMX
spring:
  jmx:
    enabled: true

logging:
  level: DEBUG
  file: /var/log/app.log

# Tomcat Server settings
server:
  port: 8080
  address: 0.0.0.0
  servletPath: /
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %t \"%r\" %s %b"
    basedir: /var/log

# Management endpoints
management:
  context-path: /manage

endpoints:
  health:
    sensitive: false
  info:
    sensitive: false
  shutdown:
    enabled: true

zzz:
  default

---
# These are the service wide settings that are applied during development
spring:
  profiles: development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

zzz:
  development

---
# A profile with windows specific paths
spring:
  profiles: windows

logging:
  file: c:/var/log/app.log
server:
  tomcat:
    basedir: c:/var/log

zzz:
  windows

